version: '2'
services:
  si-sp:    
    build: ./si-sp/
    ports:
     - "443:443"
    volumes:
    # MAPPING FOR SHIBBOLETH
     - ./si-sp/localcerts:/etc/ssl/localcerts
     - ./si-sp/shibboleth-config/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml 
     - ./si-sp/shibboleth-config/attribute-map.xml:/etc/shibboleth/attribute-map.xml
     - ./si-sp/shibboleth-logs:/var/log/shibboleth 
   # MAPPING FOR APACHE
     - ./si-sp/apache/sites-enabled:/etc/apache2/sites-enabled
     - ./si-sp/apache/php5/php.ini:/etc/php5/apache2/php.ini
   # MAPPING FOR ILIAS
     - ./si-sp/ilias-config/iliasdata:/home/www-data/iliasdata
     - ./si-sp/ilias-config/ilias.ini.php:/var/www/html/ilias/ilias.ini.php
     - ./si-sp/ilias-config/clientdata:/var/www/html/ilias/data/ilias
     - ./si-sp/ilias-config/log:/var/log/iliaslog
  mysql-db:
    image: mysql:5.7
    volumes:
     - ./mysql-db/iliasdb:/var/lib/mysql
    environment:
     MYSQL_DATABASE: ilias
     MYSQL_USER: ilias
     MYSQL_PASSWORD: secret
     MYSQL_ROOT_PASSWORD: root
     MYSQL_ROOT_HOST: "%"
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --max-connections=200 --query-cache-size=32MB --max-allowed-packet=500M
    restart: always
